version: 0.2

env:
  git-credential-helper: yes
  
phases:
  install:
    on-failure: ABORT
    commands:
      - echo "${PHASE}";
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          echo "BEGIN SAM-Backend-Build-and-Deploy";
          echo "UNPACK @turf geospatial libraries layer";
          cd jurassic-map-markers;
          tar -xvf turf-layer.tar.gz;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "BEGIN merge-preview-to-master";
        fi
      
  build:
    on-failure: ABORT
    commands:
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          echo "BUILD jurassic-map-markers SAM project";
          sam build;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "MERGE preview branch to master";
          aws codecommit merge-branches-by-fast-forward \
          --source-commit-specifier preview \
          --destination-commit-specifier master \
          --repository-name jurassic-map-mirror;
        fi
      
  post_build:
    on-failure: ABORT
    commands:
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          echo "DEPLOY JurassicMapMarkerControls SAM stack";
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset;
          echo "RESTART staggered ScheduledEvents";
          aws events disable-rule --name "JurassicMapMarkerScheduler01";
          aws events disable-rule --name "JurassicMapMarkerScheduler02";
          echo "BEGIN Scheduler01";
          aws events enable-rule --name "JurassicMapMarkerScheduler01";
          echo "WAIT 30 seconds...";
          sleep 30;
          echo "BEGIN Scheduler02";
          aws events enable-rule --name "JurassicMapMarkerScheduler02";
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "RESTART staggered ScheduledEvents";
          aws events disable-rule --name "JurassicMapMarkerScheduler01";
          aws events disable-rule --name "JurassicMapMarkerScheduler02";
          echo "BEGIN Marker Event Scheduler01";
          aws events enable-rule --name "JurassicMapMarkerScheduler01";
          echo "WAIT 30 seconds...";
          sleep 30;
          echo "BEGIN Marker Event Scheduler02";
          aws events enable-rule --name "JurassicMapMarkerScheduler02";
          echo "Pause for Amplify Deploy - 10min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 9min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 8min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 7min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 6min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 5min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 4min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 3min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 2min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - 1min remaining"";
          sleep 1m;
          echo "Pause for Amplify Deploy - preview deploy complete";
        fi