version: 0.2

env:
  git-credential-helper: yes
  
phases:
  install:
    on-failure: ABORT
    commands:
      - echo "${PHASE}";
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          echo "BEGIN SAM-Backend-Build-and-Deploy";
          echo "UNPACK @turf geospatial libraries layer";
          cd jurassic-map-markers;
          tar -xvf turf-layer.tar.gz;
          echo "BUILD jurassic-map-markers SAM project";
          sam build;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "BEGIN merge-preview-to-master";
          aws codecommit merge-branches-by-fast-forward \
          --source-commit-specifier preview \
          --destination-commit-specifier master \
          --repository-name jurassic-map-mirror;
          cd jurassic-map-markers;
        fi
      
  build:
    on-failure: ABORT
    commands:
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          echo "DEPLOY JurassicMapMarkerControls-Dev SAM stack";
          sam deploy --config-env dev --no-confirm-changeset --no-fail-on-empty-changeset;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "BUILD-and-DEPLOY JurassicMapMarkerControls-Production SAM stack";
          echo "UNPACK @turf geospatial libraries layer";
          cd jurassic-map-markers;
          tar -xvf turf-layer.tar.gz;
          echo "BUILD jurassic-map-markers SAM project";
          sam build;
          sam deploy --config-env production --no-confirm-changeset --no-fail-on-empty-changeset;
        fi
      
  post_build:
    on-failure: ABORT
    commands:
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          echo "RESTART staggered ScheduledEvents";
          aws events disable-rule --name "JurassicMapMarkerScheduler01-dev";
          aws events disable-rule --name "JurassicMapMarkerScheduler02-dev";
          echo "BEGIN Scheduler01";
          aws events enable-rule --name "JurassicMapMarkerScheduler01-dev";
          echo "WAIT 30 seconds...";
          sleep 30;
          echo "BEGIN Scheduler02";
          aws events enable-rule --name "JurassicMapMarkerScheduler02-dev";
          echo "Pause for Amplify Preview Deploy - 5min remaining";
          sleep 1m;
          echo "Pause for Amplify Preview Deploy - 4min remaining";
          sleep 1m;
          echo "Pause for Amplify Preview Deploy - 3min remaining";
          sleep 1m;
          echo "Pause for Amplify Preview Deploy - 2min remaining";
          sleep 1m;
          echo "Pause for Amplify Preview Deploy - 1min remaining";
          sleep 1m;
          echo "Pause for Amplify Preview Deploy - deploy complete";
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "RESTART staggered ScheduledEvents";
          aws events disable-rule --name "JurassicMapMarkerScheduler01";
          aws events disable-rule --name "JurassicMapMarkerScheduler02";
          echo "BEGIN Marker Event Scheduler01";
          aws events enable-rule --name "JurassicMapMarkerScheduler01";
          echo "WAIT 30 seconds...";
          sleep 30;
          echo "BEGIN Marker Event Scheduler02";
          aws events enable-rule --name "JurassicMapMarkerScheduler02";
        fi