version: 0.2

env:
  git-credential-helper: yes
  
phases:
  install:
    commands:
      - echo "${PHASE}"
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          echo "Unpack @turf geospatial libraries layer";
          cd jurassic-map-markers;
          tar -xvf turf-layer.tar.gz;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "Clone CodeCommit mirror repo, preview branch";
          git clone --branch preview https://git-codecommit.us-east-1.amazonaws.com/v1/repos/jurassic-map-mirror;
          cd jurassic-map-mirror/;
          COMMENT=$(git log -1 --pretty=%B);
        fi
      
  build:
    commands:
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          sam build;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          REQUESTID=$(aws codecommit create-pull-request --title "$COMMENT" \
          --description "Last commit comment was: $COMMENT" \
          --targets repositoryName=jurassic-map-mirror,sourceReference=preview,destinationReference=master \
          --region us-east-1 \
          --query 'pullRequest.pullRequestId');
          SOURCE_COMMIT_ID=$();
          aws codecommit merge-pull-request-by-fast-forward --pull-request-id $REQUESTID --source-commit-id 99132ab0EXAMPLE --repository-name MyDemoRepo
        fi
      
  post_build:
    commands:
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          aws codecommit merge-pull-request-by-fast-forward --pull-request-id <PULL_REQUEST_ID_FROM_PREVIOUS_COMMAND> \
          --repository-name $RepoName --region us-east-1
        fi