version: 0.2

env:
  git-credential-helper: yes
  
phases:
  install:
    commands:
      - echo "${PHASE}"
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          echo "UNPACK @turf geospatial libraries layer";
          cd jurassic-map-markers;
          tar -xvf turf-layer.tar.gz;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          
        fi
      
  build:
    commands:
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          sam build;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "MERGE preview branch to master";
          aws codecommit merge-branches-by-fast-forward \
          --source-commit-specifier preview \
          --destination-commit-specifier master \
          --repository-name jurassic-map-mirror;
        fi
      
  post_build:
    commands:
      - |
        if expr "${PHASE}" : "PREVIEW" >/dev/null; then
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset;
        fi
      - |
        if expr "${PHASE}" : "PROD" >/dev/null; then
          echo "DELETE preview branch";
          aws codecommit delete-branch --repository-name jurassic-map-mirror --branch-name preview
        fi