version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "JurassicMapMarkerControls"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9tqldvldgjtx"
s3_prefix = "JurassicMapMarkerControls"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
