AWSTemplateFormatVersion: "2010-09-09"
Description: JurassicMap movement generation, paddock testing, & scheduling components
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:16"
Resources:
  # Lambda layer resource for @Turf GeoSpatial libraries
  turfLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: turf-layer
      Description: Turf Layer for use in JurassicMap controls
      ContentUri: ./turf-layer
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete
  # Lambda function for performing map marker updates and paddock testing
  mapMarkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/mapMarkerLambda.mapMarkerHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref turfLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: JurassicMap map-markers updater function
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        # Lambda Insights permission
        - CloudWatchLambdaInsightsExecutionRolePolicy
        # Give Lambda DynamoDB read and write permissions
        - DynamoDBReadPolicy:
            TableName: mapMarker-yr5q33is7ngxno7igxguwgezye-dev
        - DynamoDBWritePolicy:
            TableName: mapMarker-yr5q33is7ngxno7igxguwgezye-dev
      Tracing: Active
      AutoPublishAlias: DevAlias
  # Lambda function for performing vehicle tours map marker updates
  mapMarkerTourVehiclesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/mapMarkerLambda.mapMarkerHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref turfLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: JurassicMap tour vehicle map-markers updater function
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        # Lambda Insights permission
        - CloudWatchLambdaInsightsExecutionRolePolicy
        # Give Lambda DynamoDB read and write permissions
        - DynamoDBReadPolicy:
            TableName: mapMarker-yr5q33is7ngxno7igxguwgezye-dev
        - DynamoDBWritePolicy:
            TableName: mapMarker-yr5q33is7ngxno7igxguwgezye-dev
      Tracing: Active
      AutoPublishAlias: live
      DeploymentPreference:
        Enabled: true
        Type: AllAtOnce
  # State Machine for orchestration map marker updates and controls
  mapMarkersUpdateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: mapMarkerUpdateMachine
      Definition:
        StartAt: Map
        States:
          Map:
            Type: Map
            Iterator:
              StartAt: MapMarkerState
              States:
                MapMarkerState:
                  Type: Task
                  Resource: !Ref mapMarkerFunction.Alias
                  End: true
            End: true
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt [ updateMachineLogGroup, Arn ]
        IncludeExecutionData: false
        Level: 'ALL'
      Tracing:
        Enabled: true
      # Custom inline policy allowing Lambda invoke, CloudWatch metrics and logs
      Policies:
        - Statement:
          - Sid: mapMarkersUpdateMachineExecutionPolicy
            Effect: Allow
            Action:
              - "lambda:InvokeFunction"
              - "cloudwatch:*"
              - "logs:*"
            Resource: "*"
      Events:
        Scheduler01:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: JurassicMapMarkerScheduler01
            Description: Schedule for running mapMarker's update State Machine every minute
            # NOTE Schedulers begin disabled, must be manually enabled
            Enabled: false
            Input: '[{"id":"parasaur01"},{"id":"parasaur02"},{"id":"parasaur03"},{"id":"brachi01"},{"id":"brachi02"},{"id":"brachi03"},{"id":"gallimimus01"},{"id":"gallimimus02"},{"id":"gallimimus03"},{"id":"gallimimus04"},{"id":"gallimimus05"},{"id":"gallimimus06"},{"id":"gallimimus07"},{"id":"gallimimus08"},{"id":"gallimimus09"},{"id":"trike01"},{"id":"trike02"},{"id":"trike03"},{"id":"dilo01"},{"id":"rex01"},{"id":"bary01"},{"id":"procerat01"},{"id":"metricanth01"},{"id":"raptor01"},{"id":"raptor02"},{"id":"raptor03"},{"id":"segi01"},{"id":"segi02"},{"id":"segi03"},{"id":"segi04"},{"id":"segi05"},{"id":"segi06"}]'
        Scheduler02:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: JurassicMapMarkerScheduler02
            Description: Schedule for running mapMarker's update State Machine every minute
            # NOTE Schedulers begin disabled, must be manually enabled
            Enabled: false
            Input: '[{"id":"parasaur01"},{"id":"parasaur02"},{"id":"parasaur03"},{"id":"brachi01"},{"id":"brachi02"},{"id":"brachi03"},{"id":"gallimimus01"},{"id":"gallimimus02"},{"id":"gallimimus03"},{"id":"gallimimus04"},{"id":"gallimimus05"},{"id":"gallimimus06"},{"id":"gallimimus07"},{"id":"gallimimus08"},{"id":"gallimimus09"},{"id":"trike01"},{"id":"trike02"},{"id":"trike03"},{"id":"dilo01"},{"id":"rex01"},{"id":"bary01"},{"id":"procerat01"},{"id":"metricanth01"},{"id":"raptor01"},{"id":"raptor02"},{"id":"raptor03"},{"id":"segi01"},{"id":"segi02"},{"id":"segi03"},{"id":"segi04"},{"id":"segi05"},{"id":"segi06"}]'
  # CloudWatch LogGroup for streaming Step Function log events
  updateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/stepfunctions/mapMarkersUpdateMachine-Logs"
  # CloudWatch Dashboard for receent-events log events
  recentActivityDashboard:
    Type: 'AWS::CloudWatch::Dashboard'
    Properties:
      DashboardBody: >-
        {"start":"-PT5M","widgets":[{"height":12,"width":12,"y":0,"x":0,"type":"log","properties":{"query":"SOURCE
        '/aws/lambda/JurassicMapMarkerControls-mapMarkerFunction-I7HmmtEB00kl' |
        fields @message | sort @ingestionTime desc | sort @requestId | sort @message
        asc | limit 30 | filter @message like /(?i)(INFO)/ | parse @message
        /(?<Event>(?<=INFO).+)/ | display
        Event","region":"us-east-1","stacked":false,"title":"","view":"table"}}]}
      DashboardName: Recent-Activity
  codePipelineReleaseTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "Jurassic Map Release Preview Topic"
      Subscription: 
        - Endpoint: "pibrocher@gmail.com"
          Protocol: "email"
      TopicName: "jurassicMapReleasePreviewTopic"
Outputs:
  managementURL:
    Description: Serverless application mgmt page URL
    Value: 'https://console.aws.amazon.com/lambda/home?region=us-east-1#/applications/JurassicMapMarkerControls'
  releasePreviewTopicARN:
    Description: Release Preview Topic ARN
    Value: !Ref codePipelineReleaseTopic