version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo "Beginnging jurassic-map GitHub and CodeCommit sync"
  pre_build:
    commands:
      - cd ~
      - git config --global user.email "bartacus@amazon.com"
      - git config --global user.name "bartacus" 
      - mkdir temp
      - cd temp/
      - echo "Clone GitHub repo"
      - git clone https://github.com/cloudbart/jurassic-map.git
      - cd jurassic-map/
      - COMMENT=$(git log -1 --pretty=%B)
      - cd .. 
      - echo "Clone CodeCommit mirror repo"
      - git clone https://git-codecommit.us-east-1.amazonaws.com/v1/repos/jurassic-map-mirror
      - echo "Copy GitHub repo to CodeCommit mirror repo"
      - cp -a jurassic-map/* jurassic-map-mirror/.
  build:
    commands:
      - cd jurassic-map-mirror/
      - git add .
      - git status
      - git commit -a -m "$COMMENT"
      - git push
  post_build:
    commands:
      - echo "Completed jurassic-map repo sync on `date`"